generator:
  sourceField: "Word (Character)"
  targetField: "Generated Speech"
  filterQuery: "deck:Chinese_1"
  overwriteTargetField: false
ankiConnect:
  url: "http://localhost:8765"
googleTextToSpeech:
  apiKeyFile: "credentials.json"
  voice:
    languageCode: "cmn-CN"
    name: "cmn-CN-Wavenet-A"
