generator:
  sourceField: "Front"
  targetField: "Back"
  filterQuery: "deck:Default"
  overwriteTargetField: false
ankiConnect:
  url: "http://localhost:8765"
googleTextToSpeech:
  apiKeyFile: "credentials.json"
  voice:
    languageCode: "cmn-CN"
    name: "cmn-CN-Wavenet-A"
